# https://docs.docker.com/compose/compose-file/#compose-and-docker-compatibility-matrix
version: '3'

# pulling images from docker hub instead of building images from source
services:
  db:
    image: mongo:4.0.1
    container_name: mongo_container
    ports:
      - 27017:27017
  proxy:
    build: ./affablebean-proxy
    image: sunshine55/affablebean-proxy:latest
    container_name: proxy_container
    ports:
      - 2600:2600

  ui:
    build: ./affablebean-ui
    image: sunshine55/affablebean-ui:latest
    container_name: ui_container
    ports:
      - 2601:2601
    depends_on:
      - ws
  ws:
    build: ./affablebean-ws
    image: sunshine55/affablebean-ws:latest
    container_name: ws_container
    ports:
      - 2602:2602
    depends_on:
      - db

networks:
  default:
    external:
      name: ms_tutorial